export const FETCH_COUNTRIES_STATES = 'FETCH_COUNTRIES_STATES';
export const FETCH_COUNTRIES_STATES_SUCCESS = 'FETCH_COUNTRIES_STATES_SUCCESS';
export const FETCH_COUNTRIES_STATES_FAILURE = 'FETCH_COUNTRIES_STATES_FAILURE';

export const UPDATE_COUNTRIES_STATES = 'UPDATE_COUNTRIES_STATES';
export const UPDATE_COUNTRIES_STATES_SUCCESS = 'UPDATE_COUNTRIES_STATES_SUCCESS';
export const UPDATE_COUNTRIES_STATES_FAILURE = 'UPDATE_COUNTRIES_STATES_FAILURE';
