export const FETCH_COUNTRIES_STATES = 'FETCH_COUNTRIES_STATES';
export const FETCH_COUNTRIES_STATES_SUCCESS = 'FETCH_COUNTRIES_STATES_SUCCESS';
export const FETCH_COUNTRIES_STATES_FAILURE = 'FETCH_COUNTRIES_STATES_FAILURE';

export const UPDATE_COUNTRY_STATE = 'UPDATE_COUNTRY_STATE';
export const UPDATE_COUNTRY_STATE_SUCCESS = 'UPDATE_COUNTRY_STATE_SUCCESS';
export const UPDATE_COUNTRY_STATE_FAILURE = 'UPDATE_COUNTRY_STATE_FAILURE';
