export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_COUNTRY_SUCCESS = 'CHANGE_COUNTRY_SUCCESS';
export const CHANGE_COUNTRY_FAILURE = 'CHANGE_COUNTRY_FAILURE';
