export const GET_COUNTRIES = 'GET_COUNTRIES';
export const TOTAL_AMOUNT = 'TOTAL_AMOUNT';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';
