export const FETCH_COUNTRIES_STATE = 'FETCH_COUNTRIES_STATE';
export const FETCH_COUNTRIES_STATE_SUCCESS = 'FETCH_COUNTRIES_STATE_SUCCESS';
export const FETCH_COUNTRIES_STATE_FAILURE = 'FETCH_COUNTRIES_STATE_FAILURE';

export const UPDATE_COUNTRIES_STATE = 'UPDATE_COUNTRIES_STATE';
export const UPDATE_COUNTRIES_STATE_SUCCESS = 'UPDATE_COUNTRIES_STATE_SUCCESS';
export const UPDATE_COUNTRIES_STATE_FAILURE = 'UPDATE_COUNTRIES_STATE_FAILURE';
