export const FETCH_GOVERNMENTS = 'FETCH_GOVERNMENTS';
export const FETCH_GOVERNMENTS_SUCCESS = 'FETCH_GOVERNMENTS_SUCCESS';
export const FETCH_GOVERNMENTS_FAILURE = 'FETCH_GOVERNMENTS_FAILURE';

export const UPDATE_GOVERNMENT = 'UPDATE_GOVERNMENT';
export const UPDATE_GOVERNMENT_SUCCESS = 'UPDATE_GOVERNMENT_SUCCESS';
export const UPDATE_GOVERNMENT_FAILURE = 'UPDATE_GOVERNMENT_FAILURE';

export const SET_ALERT = 'SET_ALERT';
